import { RESERVED_USERNAMES, checkUsername, usernameSkeleton } from './username';

/**
 * Spec 001 § 4 *Username normalisation* and § 9 "Unit suites".
 *
 * | Stage   | Rule |
 * | Accept  | NFKC, then 3–20 code points each matching [\p{L}\p{N}_] |
 * | Script  | At most one script besides Common and Inherited |
 * | Store   | confusable-skeleton(casefold(NFKC(username))) |
 * | Compare | Uniqueness and the reserved list, both on the skeleton |
 */

describe('checkUsername — Accept', () => {
  it.each(['nic', 'nico', 'nico_1', '12345', 'a'.repeat(20)])('accepts %s', (username) => {
    expect(checkUsername(username)).toEqual({ ok: true, normalized: expect.any(String) });
  });

  it.each([
    ['too short', 'no'],
    ['too long', 'a'.repeat(21)],
    ['empty', ''],
    ['a hyphen', 'ni-co'],
    ['a space', 'ni co'],
    ['a dot', 'ni.co'],
    ['an emoji', 'nico🎹'],
    ['a zero-width joiner', 'ni‍co'],
  ])('rejects %s as INVALID_FORMAT', (_label, username) => {
    expect(checkUsername(username)).toEqual({ ok: false, reason: 'INVALID_FORMAT' });
  });

  it('counts code points, not UTF-16 units', () => {
    // A three-code-point name built from astral characters is still too short
    // to be judged on length alone — it fails on the character class instead.
    expect(checkUsername('𝔫𝔦𝔠').ok).toBe(true); // NFKC folds mathematical letters to "nic"
  });

  it('normalises to NFKC before measuring', () => {
    // Fullwidth forms are the same name, and must not buy four extra characters.
    expect(checkUsername('ｎｉｃｏ')).toEqual({ ok: true, normalized: 'nico' });
  });
});

describe('checkUsername — Script', () => {
  it('accepts a single non-Latin script', () => {
    // Q18 — ASCII-only excludes most of the world's names to solve a problem
    // that has a real solution.
    expect(checkUsername('никола').ok).toBe(true);
  });

  it('accepts digits and underscores alongside any one script', () => {
    // Common and Inherited do not count as a second script.
    expect(checkUsername('никола_1').ok).toBe(true);
  });

  it('rejects a mixed-script name and names both scripts', () => {
    // "looks like Latin and Cyrillic mixed" is actionable; "invalid" is not.
    const result = checkUsername('nіco'); // Latin n, Cyrillic U+0456, Latin co
    expect(result).toEqual({
      ok: false,
      reason: 'MIXED_SCRIPT',
      scripts: expect.arrayContaining(['Latin', 'Cyrillic']),
    });
  });

  it('rejects Latin mixed with Greek', () => {
    expect(checkUsername('nicο')).toMatchObject({ reason: 'MIXED_SCRIPT' }); // Greek omicron
  });
});

describe('usernameSkeleton — Store', () => {
  it('casefolds', () => {
    expect(usernameSkeleton('NICO')).toBe('nico');
    expect(usernameSkeleton('Nico')).toBe(usernameSkeleton('nico'));
  });

  it.each([
    ['а', 'a'], // U+0430 Cyrillic small a
    ['о', 'o'], // U+043E
    ['е', 'e'], // U+0435
    ['р', 'p'], // U+0440
    ['с', 'c'], // U+0441
    ['х', 'x'], // U+0445
    ['і', 'i'], // U+0456
  ])('maps the Cyrillic homoglyph %s onto Latin %s', (cyrillic, latin) => {
    // The table is generated from Unicode TR39 confusables.txt restricted to
    // Latin, Greek and Cyrillic — regenerated by a committed script, never
    // hand-edited (§ 4).
    expect(usernameSkeleton(cyrillic)).toBe(latin);
  });

  it('is idempotent', () => {
    const once = usernameSkeleton('Аdmin');
    expect(usernameSkeleton(once)).toBe(once);
  });

  it('collapses a homoglyph spelling onto its Latin twin', () => {
    expect(usernameSkeleton('аdmin')).toBe(usernameSkeleton('admin'));
  });
});

describe('checkUsername — the reserved list', () => {
  it.each([...RESERVED_USERNAMES])('reserves %s', (reserved) => {
    expect(checkUsername(reserved)).toMatchObject({ ok: false, reason: 'RESERVED' });
  });

  it('covers every name § 7 lists', () => {
    for (const name of [
      'admin',
      'root',
      'api',
      'me',
      'settings',
      'login',
      'logout',
      'register',
      'null',
      'undefined',
      'support',
      'moderator',
      'anonymous',
      'guest',
    ]) {
      expect(checkUsername(name)).toMatchObject({ reason: 'RESERVED' });
    }
  });

  it('reserves a homoglyph spelling too', () => {
    // § 4 — this is the reason the skeleton is the unique key rather than the
    // display form.
    expect(checkUsername('аdmin')).toMatchObject({ ok: false, reason: 'RESERVED' });
  });

  it('checks the reserved list before the script rule', () => {
    // "аdmin" is Cyrillic + Latin, so both rules match it. § 4 and § 9 both say
    // the answer is 409 RESERVED, which fixes the order. Flagged at the gateway:
    // § 7's edge-case row reads the other way round.
    expect(checkUsername('аdmin')).toMatchObject({ reason: 'RESERVED' });
    expect(checkUsername('nіco')).toMatchObject({ reason: 'MIXED_SCRIPT' });
  });

  it('matches the reserved list case-insensitively', () => {
    expect(checkUsername('ADMIN')).toMatchObject({ reason: 'RESERVED' });
  });
});
